### ISSUE TITLE
v2.0.2  error

### ISSUE THREAD

**Issue by tomdavidson** [byu-oit-appdev/wabs#10]
[REQUEST] : 302 : 0.001 : / => https://cas.byu.edu/cas/login?gateway=true&service=https%3A%2F%2Fy-stg.autoreg.byu.edu%2Fwabs%2Fauth%2Fcas-ticket%3Fredirect%3Dhttps%3A%2F%2Fy-stg.autoreg.byu.edu%2F
[REQUEST] : 302 : 0.001 : /wabs/auth/cas-ticket?redirect=https://y-stg.autoreg.byu.edu/ => https://y-stg.autoreg.byu.edu/
[REQUEST] : 200 : 0.092 : /
[REQUEST] : 200 : 0.002 : /wabs/wabs.js
TypeError: Cannot read property 'toLowerCase' of undefined
    at harmonBinary (/usr/lib/node_modules/byu-wabs/node_modules/harmon/index.js:124:33)
    at /usr/lib/node_modules/byu-wabs/bin/proxy-server/proxy.js:144:9
    at /usr/lib/node_modules/byu-wabs/bin/proxy-server/proxy.js:82:13
    at Layer.handle [as handle_request] (/usr/lib/node_modules/byu-wabs/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/byu-wabs/node_modules/express/lib/router/index.js:312:13)
    at /usr/lib/node_modules/byu-wabs/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/usr/lib/node_modules/byu-wabs/node_modules/express/lib/router/index.js:330:12)
    at next (/usr/lib/node_modules/byu-wabs/node_modules/express/lib/router/index.js:271:10)
    at /usr/lib/node_modules/byu-wabs/bin/proxy-server/authenticate.js:172:13
    at Layer.handle [as handle_request] (/usr/lib/node_modules/byu-wabs/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/byu-wabs/node_modules/express/lib/router/index.js:312:13)
    at /usr/lib/node_modules/byu-wabs/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/usr/lib/node_modules/byu-wabs/node_modules/express/lib/router/index.js:330:12)
    at next (/usr/lib/node_modules/byu-wabs/node_modules/express/lib/router/index.js:271:10)
    at brownie (/usr/lib/node_modules/byu-wabs/bin/proxy-server/brownie.js:49:13)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/byu-wabs/node_modules/express/lib/router/layer.js:95:5)

**Comment by Gi60s** [comment]
I'm going to need to run your scenario in debug mode to pinpoint this.

**Comment by Gi60s** [comment]
I was able to duplicate this bug and fix it.
