### ISSUE TITLE
Can't start server with multiple --src options

### ISSUE THREAD

**Issue by arasmus8** [byu-oit-appdev/wabs#4]
I get this when trying to specify more than one --src option:

```
ajr56@ajr56-ubuntu-vm:~/map-editing$ byu-wabs --src app --src bower_components:bower_components
WABS Configuration:
 { src: [ 'app', 'bower_components:bower_components' ],
  cache: 50,
  cacheExt: 'html,htm,js,css',
  cacheMax: 1,
  endpoint: '/wabs',
  port: 9000,
  watch: true,
  authenticate: 'none',
  host: '',
  wellKnownUrl: 'https://api.byu.edu/.well-known/openid-configuration',
  brownie: 'always',
  brownieUrl: 'https://lambda.byu.edu/ae/prod/brownie-dumper/cgi/brownie-dumper.cgi/json',
  help: false }
[SRCMAP] : use cache : / => /home/ajr56/map-editing/app
[SRCMAP] : use cache : /bower_components => /home/ajr56/map-editing/bower_components
/usr/local/lib/node_modules/byu-wabs/bin/watcher.js:43
    if (parent.length < child.length) return false;
              ^

TypeError: Cannot read property 'length' of undefined
    at isSubDirectory (/usr/local/lib/node_modules/byu-wabs/bin/watcher.js:43:15)
    at /usr/local/lib/node_modules/byu-wabs/bin/watcher.js:22:36
    at Array.filter (native)
    at module.exports.Object.keys.reduce.map (/usr/local/lib/node_modules/byu-wabs/bin/watcher.js:20:10)
    at Function.Server.middleware.config [as middleware] (/usr/local/lib/node_modules/byu-wabs/bin/server/index.js:92:5)
    at Object.Server [as callback] (/usr/local/lib/node_modules/byu-wabs/bin/server/index.js:43:20)
    at Object.exports.evaluate (/usr/local/lib/node_modules/byu-wabs/node_modules/command-line-callback/bin/command-line-callback.js:141:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/byu-wabs/index.js:7:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
```

**Comment by Gi60s** [comment]
There has been a major version change since this bug was reported. This does seem to be working in the new version.
